# numpy (벡터, 행렬 다차원 데이터를 다룸)

In [20]:
import numpy as np
lst1 = [1,2,3,4,5]
lst2 = [11,12,13,14,15]

print(lst1 + lst2)

#넘파이 사용X
sum = []
for i in range(len(lst1)):
  sum.append(lst1[i]+lst2[i])

print(sum)

# 넘파이 사용시
som_of_vectors = np.add(lst1,lst2)
print(som_of_vectors,'\n')



#혹은
arr_lit1 = np.array(lst1)
arr_lit2 = np.array(lst2)

print(arr_lit1+arr_lit2)
print(arr_lit1-arr_lit2)
print(arr_lit1*arr_lit2)
print(arr_lit1+10,'\n')

#5개 원소 있고 ,는 튜플 형태라는 것을 의미
print(arr_lit1.shape)
print(arr_lit1.ndim) # 차원을 나타냄
print(arr_lit1.dtype,'\n') # 데이타 타입

print(np.arange(0,10)) # 1차원 벡터

[1, 2, 3, 4, 5, 11, 12, 13, 14, 15]
[12, 14, 16, 18, 20]
[12 14 16 18 20] 

[12 14 16 18 20]
[-10 -10 -10 -10 -10]
[11 24 39 56 75]
[11 12 13 14 15] 

(5,)
1
int64 

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
lst3 = [[1,2,3,4],[5,6,7,8],[9,10,11,12]]
print(lst3[0][2:],'\n\n')

arr_lst3 = np.array(lst3)
print(arr_lst3,'\n')
print(arr_lst3[0,2:],'\n')
print(arr_lst3.ndim,'\n')
print(arr_lst3.shape,'\n')

# 7 접근 시
print(arr_lst3[1,2])

# 11 12 접근 시
print(arr_lst3[2,2:],'\n')


print(arr_lst3[2:,2:]) # <슬라이싱 - 원소를 가져올때 차원을 유지하고 싶으면 이런 식으로 사용하면 ㅇ
print(arr_lst3[2,2:]) # <정수 인덱싱 - 배열의 차원을 하나 낮춘다

print(np.arange(1,13),'\n') # 벡터로 가져옴
print(np.arange(1,13).reshape(2,6),'\n') # 원하는 차원으로 만들어줌

arr2 = np.arange(2,26,2).reshape(3,4)
print(arr2,'\n')
print(arr2+arr_lst3,'\n')
print(arr2*arr_lst3,'\n')
print(arr2/arr_lst3,'\n')
print(arr2%arr_lst3,'\n')


In [49]:
arr2 * [1,2,3,4]

array([[ 2,  8, 18, 32],
       [10, 24, 42, 64],
       [18, 40, 66, 96]])

In [71]:
dset = {"영미":{"국어":80, "수학":90,"음악":100},
        "두현":{"국어":100, "수학":98,"음악":90},
        "준이":{"국어":95, "수학":93,"음악":92},
        }

# 가중치
weight = [1,1.2,2.0]

# 학생들의 과목별 가중치 적용 총점
sum_number = []
for name, point in dset.items():
  total = 0
  print('================')
  for i,po in enumerate(point.values()):
    total += po*weight[i]
    print(i,po)


print(sum_number)


0 80
1 188.0
2 388.0
0 100
1 217.6
2 397.6
0 95
1 206.6
2 390.6
[]
