# 넘파이(복습)

### 넘파이 arry 저장하고 불러오기

In [ ]:
import numpy as np
# from numpy, randm import randn << 이걸로 쓰면 random.randn라고 사용안해도 ㄱㅊ, 그런데 파이썬 기본 랜덤이랑 차이를 혼동 가능.

array = np.arange(0,10)
print(array)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
# 넘파이 arry 저장하고 불러오기
np.save('test_data.npy', array)

load_data = np.load('test_data.npy')

print(load_data)

[0 1 2 3 4 5 6 7 8 9]


##  Pandas
- 시리즈
- 데이타 프레임

### 시리즈
- 1차원 데이타구조, 넘파이에서 벡터와 비슷
- 열이 1개인 데이터 프레임 구조

In [ ]:
import pandas as pd

s1 = pd.Series([1,2,3,4,5]) # 인덱스 자동 생성
display(s1) # 이걸로 디스플레이 가능함

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [ ]:
s2 = pd.Series([1,2,3,4,5], index = list('abcde')) # 인덱스를 지정이 가능함
display(s2)

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [ ]:
#사전형을 이용하여 시리즈 생성{키가 인덱스를}
d={'영미': 80,'두현':90,'준이':70}
s3 = pd.Series(d)
display(s3)

영미    80
두현    90
준이    70
dtype: int64

In [ ]:
display(s3*3) #넘파이벡터 연산과 비슷하게 작용
print('=====================')
display(s3+s2) # 둘중에 하나의 키값이 없을 시 NaN 값을 반환

영미    240
두현    270
준이    210
dtype: int64

a    NaN
b    NaN
c    NaN
d    NaN
e    NaN
두현   NaN
영미   NaN
준이   NaN
dtype: float64

## 데이터 프레임
- 넘파이의 2차원 행렬구조와 비슷

In [ ]:
df1 = pd.DataFrame([[1,2,3],[4,5,6],[7,8,9],[5,6,7]]) # index , column name이 자동으로 생성함
display(df1)

0  1  2
0  1  2  3
1  4  5  6
2  7  8  9
3  5  6  7

In [ ]:
df3=pd.DataFrame([[1,2,3],[4,5,6],[6,8,9],[5,6,7]],
                 columns=["영미", "두현","준이" ],
                 index=list("abcd"))
display(df3)

영미  두현  준이
a   1   2   3
b   4   5   6
c   6   8   9
d   5   6   7

In [ ]:
# 사전형 DATAFRAME 생성 : 키가 열이름

data={"state":["Ohio","Ohio","Ohio","Nebada","Nebada","Nebada"],
      "year":["2000","2001","2002","2001","2002","2003"],
      "pop":[1.5,1.7,3.6,2.4,2.9,3.2]}
df=pd.DataFrame(data)
df

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nebada  2001  2.4
4  Nebada  2002  2.9
5  Nebada  2003  3.2

In [ ]:
# 사전형 DATAFRAME 생성 : 키가 열이름

data={"state":["Ohio","Ohio","Ohio","Nebada","Nebada","Nebada"],
      "year":["2000","2001","2002","2001","2002","2003"],
      "pop":[1.5,1.7,3.6,2.4,2.9,3.2]}
df2=pd.DataFrame(data, columns=['year','pop','state','debt']) # 이런식으로 추가 가능, 이때 없는 값은 NaN 처리를 함.
df2

year  pop   state debt
0  2000  1.5    Ohio  NaN
1  2001  1.7    Ohio  NaN
2  2002  3.6    Ohio  NaN
3  2001  2.4  Nebada  NaN
4  2002  2.9  Nebada  NaN
5  2003  3.2  Nebada  NaN

#### 열접근

In [ ]:
#df2에서 열 접근하기. 키를 인덕스로 접근
display(df2['pop']) #pop 열 하나 -> 시리즈로 나옴

print('=======================')

# 속성으로 접근
display(df2.state) #1개만 접근이 가능하다는 단점

print('==========================')

display(df2[['pop','state']]) #여러개를 동시에 접근이 가능함, 이때 데이타 프레임으로 나옴.



0    1.5
1    1.7
2    3.6
3    2.4
4    2.9
5    3.2
Name: pop, dtype: float64

0      Ohio
1      Ohio
2      Ohio
3    Nebada
4    Nebada
5    Nebada
Name: state, dtype: object

pop   state
0  1.5    Ohio
1  1.7    Ohio
2  3.6    Ohio
3  2.4  Nebada
4  2.9  Nebada
5  3.2  Nebada

In [ ]:
df2['debt'] = 16.2 # 이런식으로 값을 넣을 수 있음
display(df2)
print('\n======================================\n')
df2["debt"]=[16.2, 15.2, 3.2, 2.3, 2.5, 2.6]
display(df2)
print('\n======================================\n')
df2['degree'] = 10
display(df2)
print('\n======================================\n')

year  pop   state  debt
0  2000  1.5    Ohio  16.2
1  2001  1.7    Ohio  16.2
2  2002  3.6    Ohio  16.2
3  2001  2.4  Nebada  16.2
4  2002  2.9  Nebada  16.2
5  2003  3.2  Nebada  16.2

year  pop   state  debt
0  2000  1.5    Ohio  16.2
1  2001  1.7    Ohio  15.2
2  2002  3.6    Ohio   3.2
3  2001  2.4  Nebada   2.3
4  2002  2.9  Nebada   2.5
5  2003  3.2  Nebada   2.6

year  pop   state  debt  degree
0  2000  1.5    Ohio  16.2      10
1  2001  1.7    Ohio  15.2      10
2  2002  3.6    Ohio   3.2      10
3  2001  2.4  Nebada   2.3      10
4  2002  2.9  Nebada   2.5      10
5  2003  3.2  Nebada   2.6      10

#### 행 접근

In [ ]:
# 행은 슬라이싱 접근만 가능함
df2[:1] # 데이터 프레임 형식을 유지함
df2[3:5]

year  pop   state  debt  degree
3  2001  2.4  Nebada   2.3      10
4  2002  2.9  Nebada   2.5      10

In [ ]:
df2

year  pop   state  debt  degree
0  2000  1.5    Ohio  16.2      10
1  2001  1.7    Ohio  15.2      10
2  2002  3.6    Ohio   3.2      10
3  2001  2.4  Nebada   2.3      10
4  2002  2.9  Nebada   2.5      10
5  2003  3.2  Nebada   2.6      10

In [ ]:
#df2['pop']
display(df2['degree'])
print('\n\n===============================\n\n')
display(df2[4:6])
print('\n\n===============================\n\n')
df2[2:5][["pop",	"state",	"debt"]]

0    10
1    10
2    10
3    10
4    10
5    10
Name: degree, dtype: int64

year  pop   state  debt  degree
4  2002  2.9  Nebada   2.5      10
5  2003  3.2  Nebada   2.6      10

pop   state  debt
2  3.6    Ohio   3.2
3  2.4  Nebada   2.3
4  2.9  Nebada   2.5

In [ ]:
df2.values[1:5,1:4] # 넘파이 어레이로 가져옴

array([[1.7, 'Ohio', 15.2],
       [3.6, 'Ohio', 3.2],
       [2.4, 'Nebada', 2.3],
       [2.9, 'Nebada', 2.5]], dtype=object)

In [ ]:
data={"state":["Ohio","Ohio","Ohio","Nebada","Nebada","Nebada"],
      "year":["2000","2001","2002","2001","2002","2003"],
      "pop":[1.5,1.7,3.6,2.4,2.9,3.2]}
frame=pd.DataFrame(data, columns=["year","pop",  "state", "debt"],
                 index=list("abcdef"))
frame["debt"]=[16.2, 15.2, 3.2, 2.3,2.5,2.6]
frame["degree"]=10
display(frame)

year  pop   state  debt  degree
a  2000  1.5    Ohio  16.2      10
b  2001  1.7    Ohio  15.2      10
c  2002  3.6    Ohio   3.2      10
d  2001  2.4  Nebada   2.3      10
e  2002  2.9  Nebada   2.5      10
f  2003  3.2  Nebada   2.6      10

In [ ]:
#df2.values[1:5,1:4] # 넘파이 어레이로 가져옴

#DatFrame.iloc() << 넘파이 어레이와 같이 행렬 접근
#1. Degrre Column
display(frame.iloc[:,4])

display(frame.iloc[4:6]) # == frame.iloc[4:6, :]

display(frame.iloc[2:5, 1:4])

a    10
b    10
c    10
d    10
e    10
f    10
Name: degree, dtype: int64

year  pop   state  debt  degree
e  2002  2.9  Nebada   2.5      10
f  2003  3.2  Nebada   2.6      10

pop   state  debt
c  3.6    Ohio   3.2
d  2.4  Nebada   2.3
e  2.9  Nebada   2.5

In [ ]:
#DataFrame.loc[]=> 넘파이 어레이와 같이 행렬 접근하나 인덱스이름과 컬럼이름 사용

display(frame.loc[:, 'degree'])

display(frame.loc['e':'f']) # == frame.iloc['e':'f',:] 이름 접근은 이름을 포함해야 함

display(frame.loc['c':'e', 'pop':'debt'])

a    10
b    10
c    10
d    10
e    10
f    10
Name: degree, dtype: int64

year  pop   state  debt  degree
e  2002  2.9  Nebada   2.5      10
f  2003  3.2  Nebada   2.6      10

pop   state  debt
c  3.6    Ohio   3.2
d  2.4  Nebada   2.3
e  2.9  Nebada   2.5

In [ ]:
#display(frame)

display(frame.iloc[2:5, 3:])

display(frame.loc['c':'e','debt':])

debt  degree
c   3.2      10
d   2.3      10
e   2.5      10

debt  degree
c   3.2      10
d   2.3      10
e   2.5      10

In [ ]:
display(frame)

frame.state == "Ohio"
frame['estern'] = (frame.state == "Ohio")
display(frame)

year  pop   state  debt  degree
a  2000  1.5    Ohio  16.2      10
b  2001  1.7    Ohio  15.2      10
c  2002  3.6    Ohio   3.2      10
d  2001  2.4  Nebada   2.3      10
e  2002  2.9  Nebada   2.5      10
f  2003  3.2  Nebada   2.6      10

year  pop   state  debt  degree  estern
a  2000  1.5    Ohio  16.2      10    True
b  2001  1.7    Ohio  15.2      10    True
c  2002  3.6    Ohio   3.2      10    True
d  2001  2.4  Nebada   2.3      10   False
e  2002  2.9  Nebada   2.5      10   False
f  2003  3.2  Nebada   2.6      10   False

In [ ]:
import pandas as pd
#중첩된 자료구조도 가능함
dset={"영미":{"국어":80, "수학":90, "음악":100},
      "두현":{"국어":100, "수학":98, "음악":90},
      "준이":{"국어":95, "수학":93, "음악":92}}

deset_frame = pd.DataFrame(dset)
display(deset_frame)

score = deset_frame.T
display(score)

weight=np.array([1, 1.2,2])
total=score*weight
display(total.sum(axis = 1))

영미   두현  준이
국어   80  100  95
수학   90   98  93
음악  100   90  92

국어  수학   음악
영미   80  90  100
두현  100  98   90
준이   95  93   92

영미    388.0
두현    397.6
준이    390.6
dtype: float64

In [ ]:
dset_frame=pd.DataFrame(dset)
score=dset_frame.T
display(score)
weight=np.array([1, 1.2,2])
total=score*weight

display(score.sum(0))
display(score.sum(1))

국어  수학   음악
영미   80  90  100
두현  100  98   90
준이   95  93   92

국어    275
수학    281
음악    282
dtype: int64

영미    270
두현    288
준이    280
dtype: int64

In [ ]:
print(total.columns)
print(total.index)
print(total.values)

Index(['국어', '수학', '음악'], dtype='object')
Index(['영미', '두현', '준이'], dtype='object')
[[ 80.  108.  200. ]
 [100.  117.6 180. ]
 [ 95.  111.6 184. ]]


In [ ]:
dob = pd.Series(np.arange(5,), index = ['a','b','c','d','e'])
display(dob)

new_obj = dob.drop('c')
display(new_obj)
#오류 나는디? display(new_obj.drop(['d','c']))

a    0
b    1
c    2
d    3
e    4
dtype: int64

a    0
b    1
d    3
e    4
dtype: int64

In [ ]:
data = pd.DataFrame(np.arange(16).reshape(4,4),
                    index=['Ohio', 'Colorado', 'Utah', 'New York'],
                    columns=['one', 'two', 'three', 'four'])
display(data)
print('\n\n\n')
display(data.drop(['Colorado','Ohio']))
print('\n\n\n')
display(data.drop('two',axis = 1)) #data.drop('two',axis = 1) << 원본도 영향을 받음.
display(data.drop(['two','four'],axis = 'columns'))

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

one  three
Ohio        0      2
Colorado    4      6
Utah        8     10
New York   12     14

In [ ]:
data = pd.DataFrame(np.arange(16).reshape(4,4),
                    index=['Ohio', 'Colorado', 'Utah', 'New York'],
                    columns=['one', 'two', 'three', 'four'])

In [ ]:
data['three']>5

Ohio        False
Colorado     True
Utah         True
New York     True
Name: three, dtype: bool

In [ ]:
display(data[data['three']>5])

one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [ ]:
data = pd.DataFrame(np.arange(16).reshape(4,4),
                    index=['Ohio', 'Colorado', 'Utah', 'New York'],
                    columns=['one', 'two', 'three', 'four'])

data<5

one    two  three   four
Ohio       True   True   True   True
Colorado   True  False  False  False
Utah      False  False  False  False
New York  False  False  False  False

In [ ]:
data[data<5] = 0

data

one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [ ]:
data = pd.DataFrame(np.arange(16).reshape(4,4),
                    index=['Ohio', 'Colorado', 'Utah', 'New York'],
                    columns=['one', 'two', 'three', 'four'])

display(data.loc['Colorado',['two','three']])
print('\n\n\n')
display(data.iloc[2,[3,0,1]])
print('\n\n\n')
display(data.iloc[2])
print('\n\n\n')
display(data.iloc[[1,2],[3,0,1]])
print('\n\n\n')
display(data.loc[:'Utah','two'])
print('\n\n\n')
display(data.iloc[:,:3][data.three>5])

two      5
three    6
Name: Colorado, dtype: int64

four    11
one      8
two      9
Name: Utah, dtype: int64

one       8
two       9
three    10
four     11
Name: Utah, dtype: int64

four  one  two
Colorado     7    4    5
Utah        11    8    9

Ohio        1
Colorado    5
Utah        9
Name: two, dtype: int64

one  two  three
Colorado    4    5      6
Utah        8    9     10
New York   12   13     14

In [ ]:
data.iloc[:,0][data.one>5]
data.iloc[:,1][data.two>5]
data.iloc[:,2][data.three>5]
data.iloc[:,3][data.four>5]

Colorado     7
Utah        11
New York    15
Name: four, dtype: int64

In [ ]:
s1 = pd.Series([7.3,-2.5,3.4,1.5], index=['a','c','d','e'])
s2 = pd.Series([-2.1,3.6,-1.5,4,3.1], index=['a','c','e','f','g'])


In [ ]:
s1

a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64

In [ ]:
s2

a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64

In [ ]:
s1+s2

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [ ]:
import pandas as pd
import numpy as np

df1= pd.DataFrame(np.arange(9,).reshape((3,3)),columns=list('bcd'))
df2= pd.DataFrame(np.arange(12,).reshape((4,3)),columns=list('bde')
                  ,index=['Utah','Ohio','Texas','Oregon'])
df1+df2

b   c   d   e
0      NaN NaN NaN NaN
1      NaN NaN NaN NaN
2      NaN NaN NaN NaN
Ohio   NaN NaN NaN NaN
Oregon NaN NaN NaN NaN
Texas  NaN NaN NaN NaN
Utah   NaN NaN NaN NaN

In [ ]:
df1= pd.DataFrame(np.arange(12,).reshape((3,4)),columns=list('abcd'))
df2= pd.DataFrame(np.arange(20,).reshape((4,5)),columns=list('abcde'))

df2.loc[1,'b'] = np.nan

In [ ]:
df1

a  b   c   d
0  0  1   2   3
1  4  5   6   7
2  8  9  10  11

In [ ]:
df2

a     b   c   d   e
0   0   1.0   2   3   4
1   5   NaN   7   8   9
2  10  11.0  12  13  14
3  15  16.0  17  18  19

In [ ]:
df1+df2

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0   NaN  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [ ]:
df1.add(df2,fill_value=0)

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0   5.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [ ]:
df1.reindex(columns=df2.columns,fill_value=0)

a  b   c   d  e
0  0  1   2   3  0
1  4  5   6   7  0
2  8  9  10  11  0

#### 브로드캐스팅 연산

In [ ]:
arr = np.arange(12,).reshape((3,4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
arr[0]

array([0, 1, 2, 3])

In [ ]:
arr-arr[0]

array([[0, 0, 0, 0],
       [4, 4, 4, 4],
       [8, 8, 8, 8]])

In [ ]:
frame= pd.DataFrame(np.arange(12,).reshape((4,3)),columns=list('bde'),index=['Utah','Ohio','Texas','Oregon'])
series = frame.iloc[0]

In [ ]:
frame

b   d   e
Utah    0   1   2
Ohio    3   4   5
Texas   6   7   8
Oregon  9  10  11

In [ ]:
series

b    0
d    1
e    2
Name: Utah, dtype: int64

In [ ]:
frame - series

b  d  e
Utah    0  0  0
Ohio    3  3  3
Texas   6  6  6
Oregon  9  9  9

In [ ]:
series2 = pd.Series(range(3), index=['b', 'e', 'f'])
frame+series2

b   d     e   f
Utah    0.0 NaN   3.0 NaN
Ohio    3.0 NaN   6.0 NaN
Texas   6.0 NaN   9.0 NaN
Oregon  9.0 NaN  12.0 NaN

In [ ]:
series3 = frame['d']
frame

b   d   e
Utah    0   1   2
Ohio    3   4   5
Texas   6   7   8
Oregon  9  10  11

In [ ]:
series3

Utah       1
Ohio       4
Texas      7
Oregon    10
Name: d, dtype: int64

In [ ]:
frame.sub(series3,axis='index')

b  d  e
Utah   -1  0  1
Ohio   -1  0  1
Texas  -1  0  1
Oregon -1  0  1

In [ ]:
fram = pd.DataFrame(np.random.randn(4, 3), columns=list('bde'), index=['Utah', 'Ohio', 'Texas', 'Oregon'])
frame

b   d   e
Utah    0   1   2
Ohio    3   4   5
Texas   6   7   8
Oregon  9  10  11

In [ ]:
np.abs(frame)

b   d   e
Utah    0   1   2
Ohio    3   4   5
Texas   6   7   8
Oregon  9  10  11

#### 함수 적용과 매핑

In [ ]:
f = lambda x:x.max() - x.min()
f(np.array([1,2,3]))

2

In [ ]:
frame.apply(f)

b    9
d    9
e    9
dtype: int64

In [ ]:
frame.apply(f, axis = 1)

Utah      2
Ohio      2
Texas     2
Oregon    2
dtype: int64

In [ ]:
frame.apply(f, axis = 0)

b    9
d    9
e    9
dtype: int64

In [ ]:
frame

b   d   e
Utah    0   1   2
Ohio    3   4   5
Texas   6   7   8
Oregon  9  10  11

In [ ]:
frame.apply(f)

b    9
d    9
e    9
dtype: int64

In [ ]:
def f(x):
  return pd.Series([x.min(), x.max()])

f(np.array([1,2,3]))

frame.apply(f,axis=0)


b   d   e
0  0   1   2
1  9  10  11

In [ ]:
frame.apply(f,axis=1)

0   1
Utah    0   2
Ohio    3   5
Texas   6   8
Oregon  9  11

In [ ]:
dset={"영미":{"국어":80, "수학":90, "음악":100},
      "두현":{"국어":100, "수학":98, "음악":90},
      "준이":{"국어":95, "수학":93, "음악":92}}

In [ ]:
score = pd.DataFrame(dset).T
display(score)

국어  수학   음악
영미   80  90  100
두현  100  98   90
준이   95  93   92

In [ ]:
score["영어"] = [90,95,92,98]
score.loc['은연'] = [80,100,80,98]
# 각 학생의 평균 점수 구하기
score["평균"] = (score["국어"] + score["수학"] + score["음악"] + score["영어"]) / 4

# 각 과목의 평균점수 구하기
score.loc['과목평균'] = score.mean(axis = 0)

# 영미, 두현, 준이 각 과목에서 받은 점수와 과목 평균과 편차
score.loc['영미 편차'] = score.loc['영미'] - score.loc['과목평균']
score.loc['두현 편차'] = score.loc['두현'] - score.loc['과목평균']
score.loc['준이 편차'] = score.loc['준이'] - score.loc['과목평균']
score.loc['은연 편차'] = score.loc['은연'] - score.loc['과목평균']
display(score)

국어     수학    음악     영어       평균
영미        80     90   100  90.00     90.0
두현       100     98    90  95.00    95.75
준이        95     93    92  92.00     93.0
은연        80    100    80  98.00     89.5
과목평균   88.75  95.25  90.5  93.75  92.0625
영미 편차  -8.75  -5.25   9.5  -3.75  -2.0625
두현 편차  11.25   2.75  -0.5   1.25   3.6875
준이 편차   6.25  -2.25   1.5  -1.75   0.9375
은연 편차  -8.75   4.75 -10.5   4.25  -2.5625

# sklearn

In [ ]:
from sklearn import datasets

data = datasets.load_iris()
data

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [ ]:
#1.  data 추출 2차원
iris_data = data['data']
print(iris_data)

#2. target 추출
target_data = data['target']
print(target_data)

#3. fucher name 추출
feature_names= data['feature_names']
print(feature_names)

# target_names 1차원
target_names = data['target_names']
print(target_names)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [ ]:
# 데이터 프레임 만들기
df = pd.DataFrame(data.data, columns=data.feature_names)
display(df)



sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [ ]:
# iris 데이터의 평균 구하기
a = df.mean()
display(a)
print('\n\n\n==================================================\n')

# iris 데이터에 target 정보 추가하기
df['target'] = data.target
display(df)
print('\n\n\n==================================================\n')

# iris target의 0-> 'setosa', 1-> 'versicolor', 2-> 'virginica'로 변환
df['target'] = df['target'].map({0:"setosa", 1:"versicolor", 2:"virginica"})
display(df)
print('\n\n\n==================================================\n')

#각각의 평균 구하기
setosa=df[df['target'] == 'setosa'].mean()
versicolor= df[df['target'] == 'versicolor'].mean()
virginica = df[df['target'] == 'virginica'].mean()
print('\n\nsetosa: ',setosa,'\n\n\nversicolor: ',versicolor,'\n\n\nvirginica :',virginica)

<ipython-input-400-8fca9a1df65f>:2: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  a = df.mean()


sepal length (cm)    5.843333
sepal width (cm)     3.057333
petal length (cm)    3.758000
petal width (cm)     1.199333
dtype: float64

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     target  
0         0  
1         0  
2         0  
3         0  
4         0  
..      ...  
145       2  
146       2  
147       2  
148       2  
149       2  

[150 rows x 5 columns]

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

        target  
0       setosa  
1       setosa  
2       setosa  
3       setosa  
4       setosa  
..         ...  
145  virginica  
146  virginica  
147  virginica  
148  virginica  
149  virginica  

[150 rows x 5 columns]







setosa:  sepal length (cm)    5.006
sepal width (cm)     3.428
petal length (cm)    1.462
petal width (cm)     0.246
dtype: float64 


versicolor:  sepal length (cm)    5.936
sepal width (cm)     2.770
petal length (cm)    4.260
petal width (cm)     1.326
dtype: float64 


virginica : sepal length (cm)    6.588
sepal width (cm)     2.974
petal length (cm)    5.552
petal width (cm)     2.026
dtype: float64


<ipython-input-400-8fca9a1df65f>:17: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  setosa=df[df['target'] == 'setosa'].mean()
<ipython-input-400-8fca9a1df65f>:18: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  versicolor= df[df['target'] == 'versicolor'].mean()
<ipython-input-400-8fca9a1df65f>:19: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of 

# 새 섹션